// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCE:
 *     http-request.avsc
 */

package avro

import (
	"io"
)

type HttpRequest struct {
	Header map[string][]string
	Body   []byte
}

func DeserializeHttpRequest(r io.Reader) (*HttpRequest, error) {
	return readHttpRequest(r)
}

func NewHttpRequest() *HttpRequest {
	v := &HttpRequest{
		Header: make(map[string][]string),
	}

	return v
}

func (r *HttpRequest) Schema() string {
	return "{\"fields\":[{\"name\":\"Header\",\"type\":{\"type\":\"map\",\"values\":{\"items\":{\"name\":\"value\",\"type\":\"string\"},\"type\":\"array\"}}},{\"name\":\"Body\",\"type\":\"bytes\"}],\"name\":\"HttpRequest\",\"type\":\"record\"}"
}

func (r *HttpRequest) Serialize(w io.Writer) error {
	return writeHttpRequest(r, w)
}
